# Generated by Django 5.0.6 on 2026-03-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free Trial'), ('PRO', 'Pro')], default='FREE', max_length=20),
        ),
    ]
