# Generated by Django 6.0.3 on 2026-03-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_stockhistory'),
        ('shops', '0007_shop_currency_shop_currency_symbol'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active'], name='catalog_pro_shop_id_1d6557_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'name'], name='catalog_pro_shop_id_02eca0_idx'),
        ),
    ]
