# Generated by Django 6.0.3 on 2026-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_catalog_pro_shop_id_1d6557_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
    ]
