# Generated by Django 5.2.7 on 2025-11-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
