# Generated by Django 5.0.6 on 2026-03-08 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feedback'),
        ('shops', '0005_alter_shop_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='active_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='api.subscriptionplan'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
