# Generated by Django 5.0.6 on 2026-03-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_shop_active_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=5),
        ),
    ]
