# Generated by Django 6.0.3 on 2026-05-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shop_currency_shop_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='counter_quotation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
