# Generated by Django 6.0.3 on 2026-03-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('shops', '0007_shop_currency_shop_currency_symbol'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'mobile'], name='customers_c_shop_id_b7c2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'name'], name='customers_c_shop_id_2bfbb8_idx'),
        ),
    ]
