# Generated by Django 5.0.6 on 2026-03-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
    ]
