# Generated by Django 6.0.3 on 2026-03-10 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customers_c_shop_id_b7c2d3_idx_and_more'),
        ('sales', '0008_remove_invoice_total_amount'),
        ('shops', '0007_shop_currency_shop_currency_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['shop', 'invoice_date'], name='sales_invoi_shop_id_7982f6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['shop', 'status'], name='sales_invoi_shop_id_2f8fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['shop', 'payment_mode'], name='sales_invoi_shop_id_85d5d7_idx'),
        ),
    ]
