# Generated by Django 6.0.3 on 2026-04-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_invoice_sales_invoi_shop_id_7982f6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
