# Generated by Django 6.0.3 on 2026-05-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_invoice_discount_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('QUOTATION', 'Quotation')], default='INVOICE', max_length=20),
        ),
    ]
