# Generated by Django 6.0.3 on 2026-05-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_unit'),
        ('sales', '0011_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
    ]
