# Generated by Django 6.0.3 on 2026-05-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_invoiceitem_product_name_alter_invoiceitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
