# Generated by Django 6.0.3 on 2026-05-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_invoiceitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
